[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.9"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.9.5"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
